name: Code CI
on: [push, pull_request]
jobs:
  Build_Release:
    runs-on: ubuntu-latest
    steps:
      - name: Print all environment variables
        run: env
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: |
          docker run \
          -v $(pwd):/source \
          ghcr.io/xu-cheng/texlive-full:latest \
          /bin/bash -c "make -C /source/"
      - name: rename
        # if: startsWith(github.ref, 'refs/tags/')
        run: mv MarcellNagy_Resume.pdf MarcellNagy_Resume_${GITHUB_REF##*/}.pdf 
      - name: Store
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: "*.pdf"
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.pdf"
